######################################################################
# Automatically generated by qmake (2.01a) Sat May 2 12:42:44 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += src
TARGET = svmacs
DESTDIR = bin
RESOURCE = src/application.qrc

# Config
CONFIG += warn_on qt thread
CONFIG += debug

contains(CONFIG,debug) {
    message("Enabling logging")
    DEFINES += DEBUG_LEVEL
}

